#! /usr/bin/env python
# encoding: utf-8
#
# This file is part of the raptor project.
#
# Copyright (C) 2011 Christophe Duvernois <christophe.duvernois@gmail.com>
#
# Raptor is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Raptor is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

import sys, os

def configure(conf):
	for f in os.listdir("plugins"):
		if not f.startswith('.'):
			if os.path.isfile(os.path.abspath(f)) == False:
				if os.path.exists(os.path.abspath("plugins/%s/wscript" % f)):
					conf.msg("Checking for plugin", f)
					conf.recurse(f)

def build(bld):
	for f in os.listdir("plugins"):
		if not f.startswith('.'):
			if os.path.isfile(os.path.abspath(f)) == False:
				if os.path.exists(os.path.abspath("plugins/%s/wscript" % f)):
					bld.recurse(f)
